/**
 * @load searchSynonym
 */
INSERT INTO [functional].[searchSynonym]
([term], [synonym], [category])
VALUES
('sofa', 'sofá', 'sala'),
('sofa', 'divã', 'sala'),
('sofa', 'canapé', 'sala'),
('armario', 'armário', 'geral'),
('armario', 'guarda-roupa', 'quarto'),
('armario', 'roupeiro', 'quarto'),
('mesa', 'bancada', 'cozinha'),
('mesa', 'escrivaninha', 'escritorio'),
('cadeira', 'poltrona', 'sala'),
('cadeira', 'assento', 'geral'),
('estante', 'prateleira', 'geral'),
('estante', 'biblioteca', 'escritorio'),
('cama', 'leito', 'quarto'),
('comoda', 'cômoda', 'quarto'),
('comoda', 'gaveteiro', 'quarto'),
('rack', 'estante tv', 'sala'),
('rack', 'painel tv', 'sala'),
('buffet', 'aparador', 'sala'),
('criado', 'criado-mudo', 'quarto'),
('criado', 'mesa de cabeceira', 'quarto'),
('madeira', 'mdf', 'material'),
('madeira', 'compensado', 'material'),
('madeira', 'pinus', 'material'),
('madeira', 'carvalho', 'material'),
('metal', 'ferro', 'material'),
('metal', 'aço', 'material'),
('metal', 'aluminio', 'material'),
('metal', 'alumínio', 'material'),
('vidro', 'cristal', 'material'),
('tecido', 'estofado', 'material'),
('tecido', 'linho', 'material'),
('couro', 'courino', 'material'),
('couro', 'sintético', 'material'),
('moderno', 'contemporâneo', 'estilo'),
('moderno', 'minimalista', 'estilo'),
('classico', 'clássico', 'estilo'),
('classico', 'tradicional', 'estilo'),
('rustico', 'rústico', 'estilo'),
('rustico', 'country', 'estilo'),
('industrial', 'urbano', 'estilo'),
('retro', 'vintage', 'estilo'),
('escandinavo', 'nórdico', 'estilo');
GO